# Site settings
title: Jossware
email: ryanesc@gmail.com
description: "Jossware is an independent software consultancy dedicated to delivering quality solutions to our clients."
baseurl: ""
url: "http://jossware.com"
github_username: ryane
twitter_username: ryanesc

# Build settings
markdown: kramdown
permalink: pretty

exclude: [
  'gulpfile.js',
  'package.json'
]